seed: 42
device: cuda
precision: bf16-mixed
channels_last: true
cudnn_benchmark: true
io:
  batch_size: 64
  num_workers: 8
  prefetch_factor: 4
  persistent_workers: true
  pin_memory: true
ema:
  enable: true
  decay: 0.9999
task:
  name: bc
  action_space: continuous
run:
  max_epochs: ${optim.max_epochs}
  check_val_every_n_epoch: 1
  log_every_n_steps: 50
  devices: 1
  accelerator: auto
  num_sanity_val_steps: 0
  accumulate_grad_batches: 1
  gradient_clip_val: 1.0
  lr_monitor: true
  early_stopping:
    enable: false
    monitor: ${trainer.monitor}
    mode: ${trainer.monitor_mode}
    patience: 20
    min_delta: 0.0005
  compile:
    enable: true
    mode: max-autotune
    fullgraph: false
    dynamic: true
optim:
  name: adamw
  lr: 0.0002
  betas:
  - 0.9
  - 0.999
  weight_decay: 0.05
  max_epochs: 1
  warmup_epochs: 10
  min_lr: 1.0e-05
  fused: false
  no_decay_keys:
  - bias
  - norm
  - pos_embed
  - cls_token
sched:
  name: cosine
  t_max: null
  eta_min: 1.0e-05
  warmup_epochs: ${optim.warmup_epochs}
trainer:
  max_epochs: ${optim.max_epochs}
  check_val_every_n_epoch: 1
  log_every_n_steps: 50
  devices: 1
  accelerator: auto
  num_sanity_val_steps: 0
  accumulate_grad_batches: 1
  gradient_clip_val: 1.0
  lr_monitor: true
  early_stopping:
    enable: false
    monitor: ${trainer.monitor}
    mode: ${trainer.monitor_mode}
    patience: 20
    min_delta: 0.0005
  compile:
    enable: true
    mode: max-autotune
    fullgraph: false
    dynamic: true
data:
  name: minari_kitchen_bc
model:
  name: bc_policy
loss:
  name: mse
