@package _global_
defaults:
  - /task: bc
  - /optim: adamw
  - /sched: cosine
  - /trainer: lightning
  - _self_

model:
  name: bc_policy
  obs_dim: 60  # overwritten at runtime if datamodule exposes dims
  hidden_sizes: [256, 128]
  act_dim: 9

data:
  name: minari_kitchen_bc
  dataset_id: kitchen-complete-v1
  split_ratio: 0.98

loss:
  name: mse

optim:
  max_epochs: 3
  lr: 3e-4
  betas: [0.9, 0.999]
  weight_decay: 0.0
  fused: false

trainer:
  monitor: val_loss
  monitor_mode: min
  save_top_k: 1
  check_val_every_n_epoch: 1
  num_sanity_val_steps: 1

io:
  batch_size: 128
  num_workers: 4
  prefetch_factor: 2
  persistent_workers: false
  pin_memory: true